### ISSUE TITLE
bug in cancel subscription

### ISSUE THREAD

**Issue by bradymiller** [juggernautseinc/oe-module-lifemesh-telehealth#9]
Here is what see when try to cancel subscription:

![image](https://user-images.githubusercontent.com/278968/135330195-12e41f77-7dcb-4096-968a-670b9a043c7d.png)

![image](https://user-images.githubusercontent.com/278968/135330317-8f6048cc-f291-47b7-8e14-7a1700acbf86.png)

**Comment by bradymiller** [comment]
For security purposes, generally can't make api calls to other sites from javascript (ie. client). Better to take strategy of the api calls being redirected through openemr server (ie. send the fetch call to a openemr script that then makes the api call and returns the information). When you do this, it will also then solve issue #3

**Comment by juggernautsei** [comment]
I have started on this refactoring of the code.

**Comment by bradymiller** [comment]
![2DV](https://user-images.githubusercontent.com/278968/135555943-cd695b73-d6ac-4be7-a1d3-00ca0360cca8.gif)

**Comment by bradymiller** [comment]
fixed
